### ISSUE TITLE
Plan for new release?

### ISSUE THREAD

**Issue by xukai92** [JuliaGeometry/CoordinateTransformations.jl#53]
The current release is quite old and causes dependency issues in some cases. Any plan to realse the new master soon?

**Comment by c42f** [comment]
We currently can't release easily because JuliaRegistrator isn't installed and the people who maintain this repo don't have admin access anymore. I'm trying to sort that out in https://github.com/FugroRoames/Rotations.jl/issues/110

**Comment by c42f** [comment]
0.5.1 should be released now!
