### ISSUE TITLE
Should hypot be used for the radial coordinate?

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaGeometry/CoordinateTransformations.jl#57]
I see that the radial coordinate is computed using `sqrt(x[1]*x[1] + x[2]*x[2])`. This could potentially overflow in some cases. Do you think the use of `hypot(x[1],x[2])` would be better? The drawback would be that the code is more complex and thus could be a bit slower.

If you agree with the use of `hypot`, I can make a PR.

**Comment by andyferris** [comment]
Yes I think that is a good idea.
