### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaGeometry/CoordinateTransformations.jl#62]
Would it be possible to tag a new release?

**Comment by andyferris** [comment]
OK I think this magic incantation will work. This will be 0.6. We'll need to some more work before 1.0 (see #56).

@JuliaRegistrator register

**Comment by andyferris** [comment]
@c42f Is the best way to deal with this by manually editing the Project.toml file? Do you have experience with CompatHelper?

> The following dependencies do not have a compat entry that has an upper bound: Rotations. You may find CompatHelper helpful for keeping your compat entries up-to-date.Note: If your package works for the current version x.y.z of a dependency foo, then a compat entry foo = x.y.z implies a compatibility upper bound for packages following semver. You can additionally include earlier versions your package is compatible with. See https://julialang.github.io/Pkg.jl/v1/compatibility/ for details.

**Comment by SebastianM-C** [comment]
Shouldn't #61 have removed Rotations?
I see that the `compat` entry was removed, but not the `deps` one

**Comment by c42f** [comment]
Thanks, I merged that. I don't know about CompatHelper; haven't felt the need for it yet, but let's try it out.

**Comment by c42f** [comment]
@JuliaRegistrator register

**Comment by SebastianM-C** [comment]
The advantage of having CompatHelper would be that it would automatically open new PRs when new versions of deps appear. But in this case there is only one dependency to consider, StaticArrays, so it might be overkill.
